version: '3'

services:
  nginx:
    image: 'nginx:latest'
    volumes:
      - './_docker/nginx/conf.d/:/etc/nginx/conf.d/'
      - './:/var/www/testproject'
    ports:
      - "8080:80"
    container_name: app_nginx

  php:
    build:
      context: .
      dockerfile: _docker/php/Dockerfile
    volumes:
      - './:/var/www/testproject'
      - './_docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
    container_name: app_php

  mysql:
    image: 'mysql:8.0'
    restart: always
    volumes:
      - './tmp/db:/var/lib/mysql'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=testproject
      - MYSQL_ROOT_PASSWORD=root
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: app_mysql


